### ISSUE TITLE
Problem with decode function

### ISSUE THREAD

**Issue by AlanLiu666** [NoobZ2/Centernet-onnx-TensorRT#1]
<img width="960" alt="Problem" src="https://user-images.githubusercontent.com/110580590/187819513-9e6e15e7-d2db-46b7-89cb-64211e515db4.png">

I'm using my own image in this project because I can't find the original bus.jpg. The output is not working properly with the bbox_decode() function

**Comment by AlanLiu666** [comment]
<img width="960" alt="Problem" src="https://user-images.githubusercontent.com/110580590/187820282-f24ab852-784e-4a63-ae4a-823f44f26def.png">

**Comment by AlanLiu666** [comment]
Here is the Screen shot of the problem
![Uploading Problem.png…]()

**Comment by NoobZ2** [comment]
使用自定义数据，请阅读demo/centernet-onnx-tensorrt_readme.txt

**Comment by AlanLiu666** [comment]
> 使用自定义数据，请阅读demo/centernet-onnx-tensorrt_readme.txt

我已经按照centernet-onnx-tensorrt_readme.txt里的步骤执行过demo.py了，还是会出现上图的问题，问题出在bbox_decode()函数，output可以正常输出，可是它的shape和centernet的完全不一样。

**Comment by AlanLiu666** [comment]
> 使用自定义数据，请阅读demo/centernet-onnx-tensorrt_readme.txt

**Comment by AlanLiu666** [comment]
> 使用自定义数据，请阅读demo/centernet-onnx-tensorrt_readme.txt

<img width="960" alt="无标题" src="https://user-images.githubusercontent.com/110580590/188346092-7bd338b0-1e5c-40ff-ad08-66bce68625c2.png">

上图是推理完的output的shape
