### ISSUE TITLE
推理完的格式问题

### ISSUE THREAD

**Issue by AlanLiu666** [NoobZ2/Centernet-onnx-TensorRT#2]
<img width="960" alt="无标题" src="https://user-images.githubusercontent.com/110580590/188351941-617953d8-3285-415b-8f4a-e610e2189ab9.png">

我已经按照centernet-onnx-tensorrt_readme.txt的步骤运行过demo.py了，之前的问题还是没解决（如上图所示）。问题出在bbox_decode函数，上图包含推理完的output的shape，它和centernet需要的shape完全不一样。

**Comment by NoobZ2** [comment]
请直接修改demo.py中的bbox_decode函数，将hm,wh,reg修改为你所使用的数据的维度，因为本代码所使用的模型只有一个类别两个关键点。

**Comment by AlanLiu666** [comment]
> 请直接修改demo.py中的bbox_decode函数，将hm,wh,reg修改为你所使用的数据的维度，因为本代码所使用的模型只有一个类别两个关键点。

那你的代码可以检测多个目标吗？

**Comment by NoobZ2** [comment]
你自己训练一个多目标多关键点的模型就行，这只是推理加速的代码

**Comment by AlanLiu666** [comment]
<img width="960" alt="无标题" src="https://user-images.githubusercontent.com/110580590/188373473-4da535a1-2177-482c-b7d7-ea6c0cfd4d4a.png">
<img width="960" alt="无标题2" src="https://user-images.githubusercontent.com/110580590/188373492-63daabc4-bda6-45e6-b4ab-3b0b5d37bfca.png">
我自己训练的就是上图的效果，数据的维度我也不是很清楚，我只是个新入职的打杂的。我看文件夹里没有代码默认的ctdet_coco_dlav0_1x.trt和bus.jpg。可以把这两个发到我邮箱里吗（我的邮箱是2098697485@qq.com）,我主要是交差用（可以让代码跑起来就行了。
